[project]
name = "isojam-backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-multipart",
    "sqlalchemy>=2.0,<3.0",
    "alembic",
    "pwdlib[argon2]",
    "email-validator",
    "pyjwt",
    "bs-roformer-infer @ git+https://github.com/openmirlab/bs-roformer-infer.git@de35ada5817b878da0194ee2860253dda3a9c2b2",
]

[dependency-groups]
dev = [
    "pytest",
    "httpx2",
]