"""add users and upload ownership

Revision ID: 47d7085ef617
Revises: cc4ab351693a
Create Date: 2026-08-30 08:45:02.219033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d7085ef617'
down_revision: Union[str, Sequence[str], None] = 'cc4ab351693a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table("uploads") as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.Uuid(), nullable=False)
        )
        batch_op.create_foreign_key(
            "fk_uploads_user_id_users",
            "users",
            ["user_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads") as batch_op:
        batch_op.drop_constraint(
            "fk_uploads_user_id_users",
            type_="foreignkey",
        )
        batch_op.drop_column("user_id")

    op.drop_table("users")
    # ### end Alembic commands ###
